class CfgWeapons {
    // Hide vanilla 416s as CUP has them
    class arifle_SPAR_01_base_F;
    class arifle_SPAR_01_blk_F: arifle_SPAR_01_base_F { HIDDEN };
    class arifle_SPAR_01_khk_F: arifle_SPAR_01_base_F { HIDDEN };
    class arifle_SPAR_01_snd_F: arifle_SPAR_01_base_F { HIDDEN };

    class arifle_SPAR_01_GL_base_F;
    class arifle_SPAR_01_GL_blk_F: arifle_SPAR_01_GL_base_F { HIDDEN };
    class arifle_SPAR_01_GL_khk_F: arifle_SPAR_01_GL_base_F { HIDDEN };
    class arifle_SPAR_01_GL_snd_F: arifle_SPAR_01_GL_base_F { HIDDEN };

    class arifle_SPAR_02_base_F;
    class arifle_SPAR_02_blk_F: arifle_SPAR_02_base_F { HIDDEN };
    class arifle_SPAR_02_khk_F: arifle_SPAR_02_base_F { HIDDEN };
    class arifle_SPAR_02_snd_F: arifle_SPAR_02_base_F { HIDDEN };

    class arifle_SPAR_03_base_F;
    class arifle_SPAR_03_blk_F: arifle_SPAR_03_base_F { HIDDEN };
    class arifle_SPAR_03_khk_F: arifle_SPAR_03_base_F { HIDDEN };
    class arifle_SPAR_03_snd_F: arifle_SPAR_03_base_F { HIDDEN };

    // Hide BI RPG mess
    class Launcher_Base_F;
    class launch_RPG7_F: Launcher_Base_F { HIDDEN };

    // Hide ACP unwanted uniforms
    class U_O_V_Soldier_Viper_hex_F;
    class acp_Multicam_U_O_officer_Multicam_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_Multicam_Snow_U_O_officer_Multicam_Snow_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_POL_wz93_U_O_officer_POL_wz93_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_POL_wz93_desert_U_O_officer_POL_wz93_desert_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_ROK_Granite_U_O_officer_ROK_Granite_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_ROK_Marine_Tigerstripe_U_O_officer_ROK_Marine_Tigerstripe_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_RUS_Flora_U_O_officer_RUS_Flora_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_SE_M90_U_O_officer_SE_M90_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_Solid_Black_U_O_officer_Solid_Black_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_Solid_CoyoteBrown_U_O_officer_Solid_CoyoteBrown_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_Solid_Navy_U_O_officer_Solid_Navy_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_Solid_Olive_U_O_officer_Solid_Olive_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_Solid_Ranger_Green_U_O_officer_Solid_Ranger_Green_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_Solid_Tan_U_O_officer_Solid_Tan_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_SU_KLMK_U_O_officer_SU_KLMK_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_SU_KLMK_Winter_U_O_officer_SU_KLMK_Winter_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_SU_TTsKO_U_O_officer_SU_TTsKO_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_SY_WDL_U_O_officer_SY_WDL_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_TH_ThaiArmy_U_O_officer_TH_ThaiArmy_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_TUN_GTS_U_O_officer_TUN_GTS_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_TUR_TLF_U_O_officer_TUR_TLF_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_UA_MM14_U_O_officer_UA_MM14_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_UA_MM14_Tan_U_O_officer_UA_MM14_Tan_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_US_MARPAT_U_O_officer_US_MARPAT_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_US_MARPAT_D_U_O_officer_US_MARPAT_D_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_YU_MD89_U_O_officer_YU_MD89_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_ATACS_U_O_officer_ATACS_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_AUS_AUSCAM_U_O_officer_AUS_AUSCAM_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_CA_CADPAT_U_O_officer_CA_CADPAT_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_CA_CADPAT_Arctic_U_O_officer_CA_CADPAT_Arctic_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_CN_Type_07_Universal_U_O_officer_CN_Type_07_Universal_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_CN_Type_07_Urban_U_O_officer_CN_Type_07_Urban_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_CZ_vz95_U_O_officer_CZ_vz95_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_CZ_vz95_Desert_U_O_officer_CZ_vz95_Desert_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_DE_Flecktarn_U_O_officer_DE_Flecktarn_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_DE_Multitarn_U_O_officer_DE_Multitarn_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_EG_Egg_U_O_officer_EG_Egg_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_FI_M05_Desert_U_O_officer_FI_M05_Desert_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_FI_M05_Relish_U_O_officer_FI_M05_Relish_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_FI_M05_Snow_U_O_officer_FI_M05_Snow_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_FR_CE_U_O_officer_FR_CE_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_FR_Daguet_U_O_officer_FR_Daguet_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_HR_CROPAT_U_O_officer_HR_CROPAT_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_IDN_Kopassus_U_O_officer_IDN_Kopassus_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_IL_IDF_U_O_officer_IL_IDF_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_JP_GSDF_U_O_officer_JP_GSDF_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN };
    class acp_LU_Waldtarndruck_U_O_officer_LU_Waldtarndruck_hex_F: U_O_V_Soldier_Viper_hex_F { HIDDEN }

    class U_O_CombatUniform_ocamo;
    class acp_Multicam_U_O_CombatUniform_Multicam: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_Multicam_Snow_U_O_CombatUniform_Multicam_Snow: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_POL_wz93_U_O_CombatUniform_POL_wz93: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_POL_wz93_desert_U_O_CombatUniform_POL_wz93_desert: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_ROK_Granite_U_O_CombatUniform_ROK_Granite: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_ROK_Marine_Tigerstripe_U_O_CombatUniform_ROK_Marine_Tigerstripe: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_RUS_Flora_U_O_CombatUniform_RUS_Flora: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_SE_M90_U_O_CombatUniform_SE_M90: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_Solid_Black_U_O_CombatUniform_Solid_Black: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_Solid_CoyoteBrown_U_O_CombatUniform_Solid_CoyoteBrown: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_Solid_Navy_U_O_CombatUniform_Solid_Navy: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_Solid_Olive_U_O_CombatUniform_Solid_Olive: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_Solid_Ranger_Green_U_O_CombatUniform_Solid_Ranger_Green: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_Solid_Tan_U_O_CombatUniform_Solid_Tan: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_SU_KLMK_U_O_CombatUniform_SU_KLMK: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_SU_KLMK_Winter_U_O_CombatUniform_SU_KLMK_Winter: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_SU_TTsKO_U_O_CombatUniform_SU_TTsKO: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_SY_WDL_U_O_CombatUniform_SY_WDL: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_TH_ThaiArmy_U_O_CombatUniform_TH_ThaiArmy: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_TUN_GTS_U_O_CombatUniform_TUN_GTS: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_TUR_TLF_U_O_CombatUniform_TUR_TLF: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_UA_MM14_U_O_CombatUniform_UA_MM14: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_UA_MM14_Tan_U_O_CombatUniform_UA_MM14_Tan: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_US_MARPAT_U_O_CombatUniform_US_MARPAT: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_US_MARPAT_D_U_O_CombatUniform_US_MARPAT_D: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_YU_MD89_U_O_CombatUniform_YU_MD89: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_ATACS_U_O_CombatUniform_ATACS: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_AUS_AUSCAM_U_O_CombatUniform_AUS_AUSCAM: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_CA_CADPAT_U_O_CombatUniform_CA_CADPAT: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_CA_CADPAT_Arctic_U_O_CombatUniform_CA_CADPAT_Arctic: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_CN_Type_07_Universal_U_O_CombatUniform_CN_Type_07_Universal: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_CN_Type_07_Urban_U_O_CombatUniform_CN_Type_07_Urban: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_CZ_vz95_U_O_CombatUniform_CZ_vz95: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_CZ_vz95_Desert_U_O_CombatUniform_CZ_vz95_Desert: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_DE_Flecktarn_U_O_CombatUniform_DE_Flecktarn: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_DE_Multitarn_U_O_CombatUniform_DE_Multitarn: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_EG_Egg_U_O_CombatUniform_EG_Egg: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_FI_M05_Desert_U_O_CombatUniform_FI_M05_Desert: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_FI_M05_Relish_U_O_CombatUniform_FI_M05_Relish: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_FI_M05_Snow_U_O_CombatUniform_FI_M05_Snow: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_FR_CE_U_O_CombatUniform_FR_CE: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_FR_Daguet_U_O_CombatUniform_FR_Daguet: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_HR_CROPAT_U_O_CombatUniform_HR_CROPAT: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_IDN_Kopassus_U_O_CombatUniform_IDN_Kopassus: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_IL_IDF_U_O_CombatUniform_IL_IDF: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_JP_GSDF_U_O_CombatUniform_JP_GSDF: U_O_CombatUniform_ocamo { HIDDEN };
    class acp_LU_Waldtarndruck_U_O_CombatUniform_LU_Waldtarndruck: U_O_CombatUniform_ocamo { HIDDEN };

    // Hide ACP unwanted headGear
    class H_HelmetSpecO_ocamo;
    class acp_Multicam_H_HelmetSpecO_Multicam: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_Multicam_Snow_H_HelmetSpecO_Multicam_Snow: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_POL_wz93_H_HelmetSpecO_POL_wz93: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_POL_wz93_desert_H_HelmetSpecO_POL_wz93_desert: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_ROK_Granite_H_HelmetSpecO_ROK_Granite: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_ROK_Marine_Tigerstripe_H_HelmetSpecO_ROK_Marine_Tigerstripe: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_RUS_Flora_H_HelmetSpecO_RUS_Flora: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_SE_M90_H_HelmetSpecO_SE_M90: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_Solid_Black_H_HelmetSpecO_Solid_Black: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_Solid_CoyoteBrown_H_HelmetSpecO_Solid_CoyoteBrown: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_Solid_Navy_H_HelmetSpecO_Solid_Navy: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_Solid_Olive_H_HelmetSpecO_Solid_Olive: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_Solid_Ranger_Green_H_HelmetSpecO_Solid_Ranger_Green: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_Solid_Tan_H_HelmetSpecO_Solid_Tan: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_SU_KLMK_H_HelmetSpecO_SU_KLMK: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_SU_KLMK_Winter_H_HelmetSpecO_SU_KLMK_Winter: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_SU_TTsKO_H_HelmetSpecO_SU_TTsKO: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_SY_WDL_H_HelmetSpecO_SY_WDL: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_TH_ThaiArmy_H_HelmetSpecO_TH_ThaiArmy: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_TUN_GTS_H_HelmetSpecO_TUN_GTS: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_TUR_TLF_H_HelmetSpecO_TUR_TLF: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_UA_MM14_H_HelmetSpecO_UA_MM14: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_UA_MM14_Tan_H_HelmetSpecO_UA_MM14_Tan: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_US_MARPAT_H_HelmetSpecO_US_MARPAT: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_US_MARPAT_D_H_HelmetSpecO_US_MARPAT_D: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_YU_MD89_H_HelmetSpecO_YU_MD89: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_ATACS_H_HelmetSpecO_ATACS: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_AUS_AUSCAM_H_HelmetSpecO_AUS_AUSCAM: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_CA_CADPAT_H_HelmetSpecO_CA_CADPAT: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_CA_CADPAT_Arctic_H_HelmetSpecO_CA_CADPAT_Arctic: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_CN_Type_07_Universal_H_HelmetSpecO_CN_Type_07_Universal: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_CN_Type_07_Urban_H_HelmetSpecO_CN_Type_07_Urban: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_CZ_vz95_H_HelmetSpecO_CZ_vz95: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_CZ_vz95_Desert_H_HelmetSpecO_CZ_vz95_Desert: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_DE_Flecktarn_H_HelmetSpecO_DE_Flecktarn: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_DE_Multitarn_H_HelmetSpecO_DE_Multitarn: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_EG_Egg_H_HelmetSpecO_EG_Egg: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_FI_M05_Desert_H_HelmetSpecO_FI_M05_Desert: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_FI_M05_Relish_H_HelmetSpecO_FI_M05_Relish: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_FI_M05_Snow_H_HelmetSpecO_FI_M05_Snow: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_FR_CE_H_HelmetSpecO_FR_CE: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_FR_Daguet_H_HelmetSpecO_FR_Daguet: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_HR_CROPAT_H_HelmetSpecO_HR_CROPAT: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_IDN_Kopassus_H_HelmetSpecO_IDN_Kopassus: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_IL_IDF_H_HelmetSpecO_IL_IDF: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_JP_GSDF_H_HelmetSpecO_JP_GSDF: H_HelmetSpecO_ocamo { HIDDEN }
    class acp_LU_Waldtarndruck_H_HelmetSpecO_LU_Waldtarndruck : H_HelmetSpecO_ocamo { HIDDEN }

    class H_HelmetLeaderO_ocamo;
    class acp_Multicam_H_HelmetLeaderO_Multicam: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_Multicam_Snow_H_HelmetLeaderO_Multicam_Snow: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_POL_wz93_H_HelmetLeaderO_POL_wz93: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_POL_wz93_desert_H_HelmetLeaderO_POL_wz93_desert: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_ROK_Granite_H_HelmetLeaderO_ROK_Granite: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_ROK_Marine_Tigerstripe_H_HelmetLeaderO_ROK_Marine_Tigerstripe: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_RUS_Flora_H_HelmetLeaderO_RUS_Flora: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_SE_M90_H_HelmetLeaderO_SE_M90: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_Solid_Black_H_HelmetLeaderO_Solid_Black: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_Solid_CoyoteBrown_H_HelmetLeaderO_Solid_CoyoteBrown: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_Solid_Navy_H_HelmetLeaderO_Solid_Navy: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_Solid_Olive_H_HelmetLeaderO_Solid_Olive: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_Solid_Ranger_Green_H_HelmetLeaderO_Solid_Ranger_Green: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_Solid_Tan_H_HelmetLeaderO_Solid_Tan: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_SU_KLMK_H_HelmetLeaderO_SU_KLMK: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_SU_KLMK_Winter_H_HelmetLeaderO_SU_KLMK_Winter: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_SU_TTsKO_H_HelmetLeaderO_SU_TTsKO: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_SY_WDL_H_HelmetLeaderO_SY_WDL: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_TH_ThaiArmy_H_HelmetLeaderO_TH_ThaiArmy: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_TUN_GTS_H_HelmetLeaderO_TUN_GTS: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_TUR_TLF_H_HelmetLeaderO_TUR_TLF: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_UA_MM14_H_HelmetLeaderO_UA_MM14: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_UA_MM14_Tan_H_HelmetLeaderO_UA_MM14_Tan: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_US_MARPAT_H_HelmetLeaderO_US_MARPAT: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_US_MARPAT_D_H_HelmetLeaderO_US_MARPAT_D: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_YU_MD89_H_HelmetLeaderO_YU_MD89: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_ATACS_H_HelmetLeaderO_ATACS: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_AUS_AUSCAM_H_HelmetLeaderO_AUS_AUSCAM: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_CA_CADPAT_H_HelmetLeaderO_CA_CADPAT: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_CA_CADPAT_Arctic_H_HelmetLeaderO_CA_CADPAT_Arctic: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_CN_Type_07_Universal_H_HelmetLeaderO_CN_Type_07_Universal: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_CN_Type_07_Urban_H_HelmetLeaderO_CN_Type_07_Urban: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_CZ_vz95_H_HelmetLeaderO_CZ_vz95: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_CZ_vz95_Desert_H_HelmetLeaderO_CZ_vz95_Desert: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_DE_Flecktarn_H_HelmetLeaderO_DE_Flecktarn: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_DE_Multitarn_H_HelmetLeaderO_DE_Multitarn: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_EG_Egg_H_HelmetLeaderO_EG_Egg: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_FI_M05_Desert_H_HelmetLeaderO_FI_M05_Desert: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_FI_M05_Relish_H_HelmetLeaderO_FI_M05_Relish: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_FI_M05_Snow_H_HelmetLeaderO_FI_M05_Snow: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_FR_CE_H_HelmetLeaderO_FR_CE: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_FR_Daguet_H_HelmetLeaderO_FR_Daguet: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_HR_CROPAT_H_HelmetLeaderO_HR_CROPAT: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_IDN_Kopassus_H_HelmetLeaderO_IDN_Kopassus: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_IL_IDF_H_HelmetLeaderO_IL_IDF: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_JP_GSDF_H_HelmetLeaderO_JP_GSDF: H_HelmetLeaderO_ocamo { HIDDEN };
    class acp_LU_Waldtarndruck_H_HelmetLeaderO_LU_Waldtarndruck: H_HelmetLeaderO_ocamo { HIDDEN };

    class H_HelmetO_ocamo;
    class acp_Multicam_H_HelmetO_Multicam: H_HelmetO_ocamo { HIDDEN };
    class acp_Multicam_Snow_H_HelmetO_Multicam_Snow: H_HelmetO_ocamo { HIDDEN };
    class acp_POL_wz93_H_HelmetO_POL_wz93: H_HelmetO_ocamo { HIDDEN };
    class acp_POL_wz93_desert_H_HelmetO_POL_wz93_desert: H_HelmetO_ocamo { HIDDEN };
    class acp_ROK_Granite_H_HelmetO_ROK_Granite: H_HelmetO_ocamo { HIDDEN };
    class acp_ROK_Marine_Tigerstripe_H_HelmetO_ROK_Marine_Tigerstripe: H_HelmetO_ocamo { HIDDEN };
    class acp_RUS_Flora_H_HelmetO_RUS_Flora: H_HelmetO_ocamo { HIDDEN };
    class acp_SE_M90_H_HelmetO_SE_M90: H_HelmetO_ocamo { HIDDEN };
    class acp_Solid_Black_H_HelmetO_Solid_Black: H_HelmetO_ocamo { HIDDEN };
    class acp_Solid_CoyoteBrown_H_HelmetO_Solid_CoyoteBrown: H_HelmetO_ocamo { HIDDEN };
    class acp_Solid_Navy_H_HelmetO_Solid_Navy: H_HelmetO_ocamo { HIDDEN };
    class acp_Solid_Olive_H_HelmetO_Solid_Olive: H_HelmetO_ocamo { HIDDEN };
    class acp_Solid_Ranger_Green_H_HelmetO_Solid_Ranger_Green: H_HelmetO_ocamo { HIDDEN };
    class acp_Solid_Tan_H_HelmetO_Solid_Tan: H_HelmetO_ocamo { HIDDEN };
    class acp_SU_KLMK_H_HelmetO_SU_KLMK: H_HelmetO_ocamo { HIDDEN };
    class acp_SU_KLMK_Winter_H_HelmetO_SU_KLMK_Winter: H_HelmetO_ocamo { HIDDEN };
    class acp_SU_TTsKO_H_HelmetO_SU_TTsKO: H_HelmetO_ocamo { HIDDEN };
    class acp_SY_WDL_H_HelmetO_SY_WDL: H_HelmetO_ocamo { HIDDEN };
    class acp_TH_ThaiArmy_H_HelmetO_TH_ThaiArmy: H_HelmetO_ocamo { HIDDEN };
    class acp_TUN_GTS_H_HelmetO_TUN_GTS: H_HelmetO_ocamo { HIDDEN };
    class acp_TUR_TLF_H_HelmetO_TUR_TLF: H_HelmetO_ocamo { HIDDEN };
    class acp_UA_MM14_H_HelmetO_UA_MM14: H_HelmetO_ocamo { HIDDEN };
    class acp_UA_MM14_Tan_H_HelmetO_UA_MM14_Tan: H_HelmetO_ocamo { HIDDEN };
    class acp_US_MARPAT_H_HelmetO_US_MARPAT: H_HelmetO_ocamo { HIDDEN };
    class acp_US_MARPAT_D_H_HelmetO_US_MARPAT_D: H_HelmetO_ocamo { HIDDEN };
    class acp_YU_MD89_H_HelmetO_YU_MD89: H_HelmetO_ocamo { HIDDEN };
    class acp_ATACS_H_HelmetO_ATACS: H_HelmetO_ocamo { HIDDEN };
    class acp_AUS_AUSCAM_H_HelmetO_AUS_AUSCAM: H_HelmetO_ocamo { HIDDEN };
    class acp_CA_CADPAT_H_HelmetO_CA_CADPAT: H_HelmetO_ocamo { HIDDEN };
    class acp_CA_CADPAT_Arctic_H_HelmetO_CA_CADPAT_Arctic: H_HelmetO_ocamo { HIDDEN };
    class acp_CN_Type_07_Universal_H_HelmetO_CN_Type_07_Universal: H_HelmetO_ocamo { HIDDEN };
    class acp_CN_Type_07_Urban_H_HelmetO_CN_Type_07_Urban: H_HelmetO_ocamo { HIDDEN };
    class acp_CZ_vz95_H_HelmetO_CZ_vz95: H_HelmetO_ocamo { HIDDEN };
    class acp_CZ_vz95_Desert_H_HelmetO_CZ_vz95_Desert: H_HelmetO_ocamo { HIDDEN };
    class acp_DE_Flecktarn_H_HelmetO_DE_Flecktarn: H_HelmetO_ocamo { HIDDEN };
    class acp_DE_Multitarn_H_HelmetO_DE_Multitarn: H_HelmetO_ocamo { HIDDEN };
    class acp_EG_Egg_H_HelmetO_EG_Egg: H_HelmetO_ocamo { HIDDEN };
    class acp_FI_M05_Desert_H_HelmetO_FI_M05_Desert: H_HelmetO_ocamo { HIDDEN };
    class acp_FI_M05_Relish_H_HelmetO_FI_M05_Relish: H_HelmetO_ocamo { HIDDEN };
    class acp_FI_M05_Snow_H_HelmetO_FI_M05_Snow: H_HelmetO_ocamo { HIDDEN };
    class acp_FR_CE_H_HelmetO_FR_CE: H_HelmetO_ocamo { HIDDEN };
    class acp_FR_Daguet_H_HelmetO_FR_Daguet: H_HelmetO_ocamo { HIDDEN };
    class acp_HR_CROPAT_H_HelmetO_HR_CROPAT: H_HelmetO_ocamo { HIDDEN };
    class acp_IDN_Kopassus_H_HelmetO_IDN_Kopassus: H_HelmetO_ocamo { HIDDEN };
    class acp_IL_IDF_H_HelmetO_IL_IDF: H_HelmetO_ocamo { HIDDEN };
    class acp_JP_GSDF_H_HelmetO_JP_GSDF: H_HelmetO_ocamo { HIDDEN };
    class acp_LU_Waldtarndruck_H_HelmetO_LU_Waldtarndruck: H_HelmetO_ocamo { HIDDEN };

    class H_HelmetO_ViperSP_hex_F;
    class acp_Multicam_H_HelmetO_ViperSP_Multicam_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_Multicam_Snow_H_HelmetO_ViperSP_Multicam_Snow_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_POL_wz93_H_HelmetO_ViperSP_POL_wz93_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_POL_wz93_desert_H_HelmetO_ViperSP_POL_wz93_desert_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_ROK_Granite_H_HelmetO_ViperSP_ROK_Granite_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_ROK_Marine_Tigerstripe_H_HelmetO_ViperSP_ROK_Marine_Tigerstripe_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_RUS_Flora_H_HelmetO_ViperSP_RUS_Flora_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_SE_M90_H_HelmetO_ViperSP_SE_M90_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_Solid_Black_H_HelmetO_ViperSP_Solid_Black_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_Solid_CoyoteBrown_H_HelmetO_ViperSP_Solid_CoyoteBrown_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_Solid_Navy_H_HelmetO_ViperSP_Solid_Navy_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_Solid_Olive_H_HelmetO_ViperSP_Solid_Olive_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_Solid_Ranger_Green_H_HelmetO_ViperSP_Solid_Ranger_Green_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_Solid_Tan_H_HelmetO_ViperSP_Solid_Tan_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_SU_KLMK_H_HelmetO_ViperSP_SU_KLMK_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_SU_KLMK_Winter_H_HelmetO_ViperSP_SU_KLMK_Winter_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_SU_TTsKO_H_HelmetO_ViperSP_SU_TTsKO_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_SY_WDL_H_HelmetO_ViperSP_SY_WDL_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_TH_ThaiArmy_H_HelmetO_ViperSP_TH_ThaiArmy_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_TUN_GTS_H_HelmetO_ViperSP_TUN_GTS_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_TUR_TLF_H_HelmetO_ViperSP_TUR_TLF_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_UA_MM14_H_HelmetO_ViperSP_UA_MM14_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_UA_MM14_Tan_H_HelmetO_ViperSP_UA_MM14_Tan_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_US_MARPAT_H_HelmetO_ViperSP_US_MARPAT_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_US_MARPAT_D_H_HelmetO_ViperSP_US_MARPAT_D_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_YU_MD89_H_HelmetO_ViperSP_YU_MD89_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_ATACS_H_HelmetO_ViperSP_ATACS_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_AUS_AUSCAM_H_HelmetO_ViperSP_AUS_AUSCAM_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_CA_CADPAT_H_HelmetO_ViperSP_CA_CADPAT_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_CA_CADPAT_Arctic_H_HelmetO_ViperSP_CA_CADPAT_Arctic_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_CN_Type_07_Universal_H_HelmetO_ViperSP_CN_Type_07_Universal_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_CN_Type_07_Urban_H_HelmetO_ViperSP_CN_Type_07_Urban_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_CZ_vz95_H_HelmetO_ViperSP_CZ_vz95_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_CZ_vz95_Desert_H_HelmetO_ViperSP_CZ_vz95_Desert_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_DE_Flecktarn_H_HelmetO_ViperSP_DE_Flecktarn_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_DE_Multitarn_H_HelmetO_ViperSP_DE_Multitarn_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_EG_Egg_H_HelmetO_ViperSP_EG_Egg_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_FI_M05_Desert_H_HelmetO_ViperSP_FI_M05_Desert_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_FI_M05_Relish_H_HelmetO_ViperSP_FI_M05_Relish_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_FI_M05_Snow_H_HelmetO_ViperSP_FI_M05_Snow_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_FR_CE_H_HelmetO_ViperSP_FR_CE_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_FR_Daguet_H_HelmetO_ViperSP_FR_Daguet_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_HR_CROPAT_H_HelmetO_ViperSP_HR_CROPAT_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_IDN_Kopassus_H_HelmetO_ViperSP_IDN_Kopassus_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_IL_IDF_H_HelmetO_ViperSP_IL_IDF_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_JP_GSDF_H_HelmetO_ViperSP_JP_GSDF_F: H_HelmetO_ViperSP_hex_F { HIDDEN };
    class acp_LU_Waldtarndruck_H_HelmetO_ViperSP_LU_Waldtarndruck_F : H_HelmetO_ViperSP_hex_F { HIDDEN };
};