name = "Ark Inhouse"
prefix = "ark"
author = "ARK"

[files]
include = [
    "README.md"
]

[version]
path = "addons/ark_main/script_version.hpp"
git_hash = 0

[hemtt.config]
preset = "Hemtt"

[hemtt.release]
folder = "ark_inhouse"
